package com.example.blog.board;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;

import java.sql.Timestamp;

@AllArgsConstructor
@Table(name = "board_tb") // 이름 설정 안하면 Board가 된다.
@NoArgsConstructor // DB에서 조회해서 가져온 RS(result set)를 디폴트 생성자를 호출해서 new하고 값을 채워준다.
@Entity
@Getter
public class Board {
    // @Entity는 기본키가 필요해서 설정
    @Id // import jakarta (자카르타는 Indonesia에 있다.)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//   로그에 generated by default as identity -> AUTO_INCREMENT랑 같은 의미
    private Integer id;
    private String title;
    private String content;

    @CreationTimestamp
    private Timestamp createdAt;

    // setter는 함부로 만들면 안된다. 필요한 부분만 수정하는 메서드 작성
    public void update(String title, String content) {
        this.title = title;
        this.content = content;
    }
}
